name: dart_cloud_email_client_api
description: Forward Email API client for Dart with Dio.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dependencies:
  dio: ^5.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  http_mock_adapter: ^0.6.1
