name: s3_client_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.4
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
