name: cloudflare_client
description: Dart client for Cloudflare API to manage DNS records
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.5.0
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^6.0.0
