name: dart_cloud_backend
description: Backend server for hosting and managing Dart serverless functions
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_multipart: ^2.0.1
  uuid: ^4.1.0
  path: ^1.9.1
  archive: ^4.0.7
  postgres: ^3.5.9
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.3.1
  dotenv: ^4.2.0
  analyzer: ^9.0.0
  database: 
    path: packages/database
  s3_client_dart:
    path: ../tools/dart_packages/s3_client_dart
    # git:
    #   url: https://github.com/liodali/ContainerPub.git
    #   path: tools/dart_packages/s3_client_dart
    #   ref: 1f39b55a582cd97a6890e53e8fe70738efd11876

dev_dependencies:
  lints: ^6.0.0
  #test: ^1.26.3
