name: dart_cloud_backend
description: Backend server for hosting and managing Dart serverless functions
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_multipart: ^2.0.1
  uuid: ^4.1.0
  path: ^1.9.1
  archive: ^4.0.7
  postgres: ^3.5.9
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.3.1
  dotenv: ^4.2.0
  hive_ce: ^2.15.1
  crypto: ^3.0.6
  collection: ^1.19.1
  yaml: ^3.1.3
  json2yaml: ^3.0.1
  zard: ^0.0.25
  name_generator:
    path: packages/name_generator
  characters: ^1.4.1
  database:
    path: packages/database
  s3_native_http_client:
    path: ../tools/dart_packages/s3_native_http_client
  dart_cloud_email_client_api:
    path: ../tools/dart_packages/dart_cloud_email_client_api
  cli_util: ^0.4.2
  sentry: ^9.9.1
  #s3_client_dart:
  #  path: ../tools/dart_packages/s3_client_dart
  # git:
  #   url: https://github.com/liodali/ContainerPub.git
  #   path: tools/dart_packages/s3_client_dart
  #   ref: 1f39b55a582cd97a6890e53e8fe70738efd11876

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  dart_cloud_deploy_cli:
    path: ../tools/dart_packages/dart_cloud_deploy_cli