name: dart_cloud_cli
description: CLI tool for deploying and managing Dart serverless functions
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  path: ^1.9.0
  yaml: ^3.1.2
  cli_util: ^0.4.0
  archive: ^3.4.0
  io: ^1.0.4
  analyzer: ^9.0.0
  hive_ce: ^2.15.1

dev_dependencies:
  lints: ^6.0.0
  dart_style: ^3.1.2
  #test: ^1.24.0

dependency_overrides:
  analyzer: ^9.0.0
executables:
  dart_cloud: main
