name: cloud_api_client
description: API Client for Dart Cloud Backend
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.5
  crypto: ^3.0.3
  json_annotation: ^4.8.0
  hive_ce: ^2.15.1
  intl: ^0.20.0

dev_dependencies:
  build_runner: ^2.3.3
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
