name: dart_cloud_function
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/liodali/ContainerPub

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
