name: dart_cloud_function
description: Dart Cloud Function package for serverless functions in Dart
version: 0.2.0
repository: https://github.com/liodali/ContainerPub

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  dart_cloud_logger: ^0.2.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
