name: s3_native_http_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  aws_signature_v4: ^0.6.10
  http: ^1.6.0
  aws_common: ^0.7.12
  xml: ^6.6.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
