name: dart_cloud_logger
description: A simple logging utility for Dart cloud functions
version: 0.1.0
repository: https://github.com/liodali/ContainerPub

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
