name: s3_client_dart
description: s3 client for dart based on go sdk
tags:
  - s3
  - client
version: 0.1.5
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.4
  path: ^1.9.1
  http: ^1.2.0
  archive: ^4.0.7
  collection: ^1.19.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
