name: email_service
description: Email service for sending OTP verification emails using Forward Email API.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  dart_cloud_email_client_api:
    path: ../../../tools/dart_packages/dart_cloud_email_client_api

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  mocktail: ^1.0.4
